# Generated by Django 4.2.2 on 2023-07-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authorblog_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorblog',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authorblog',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='authorblog',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='authorblog',
            name='user_permissions',
        ),
    ]
