# Generated by Django 4.2.2 on 2023-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
